services:
  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    networks:
        - django-celery

  django:
    container_name: django
    build:
      context: ./eshop
      dockerfile: Dockerfile
    image: django-celery
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./eshop:/app/
    ports:
      - "8000:8000"
    networks:
      - django-celery
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./eshop
      dockerfile: Dockerfile
    image: celery
    command: celery --app=config worker -l INFO -Q queue1
    volumes:
      - ./eshop:/app/
    networks:
      - django-celery
    depends_on:
      - redis
      - django

  standalone_celery:
    container_name: standalone-celery
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    image: standalone-celery
    command: celery -A celery_base worker -l INFO -Q queue2
    volumes:
      - ./celery_worker:/app
    networks:
      - django-celery
    depends_on:
      - redis
      - django

networks:
  django-celery:
    name: django-celery
    driver: bridge
